<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle( $this->translate('Fuel Finder') )->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile( 'http://maps.googleapis.com/maps/api/js?sensor=true', 'text/javascript' )
        ; ?>
        
        <script type="text/javascript">
            var map;
            function initialise()
            {
                var mapOptions = {
                    center: new google.maps.LatLng( -34.397, 150.644 ),
                    zoom: 8
                };
                map = new google.maps.Map( document.getElementById( "map" ), mapOptions );
            }
            $( 'document' ).ready(
                function()
                {
                    initialise();
                    $( "#geolocation" ).submit(
                        function( event )
                        {
                            $( '#results' ).empty();
                            event.preventDefault();
                            $.get( $( this ).attr( 'action' ),
                                   $( this ).serializeArray(),
                                   function( data )
                                   {
                                       $.each( data.results,
                                               function( index, value )
                                               {
                                                   $( "#results" ).append( $( '<li/>', { 'text': value.formatted_address } ) );
                                                   map.fitBounds(new google.maps.LatLngBounds(
                                                                        new google.maps.LatLng( value.geometry.bounds.southwest.lat, value.geometry.bounds.southwest.lng ),
                                                                        new google.maps.LatLng( value.geometry.bounds.northeast.lat, value.geometry.bounds.northeast.lng ) )
                                                                  );
                                                    console.log( value.geometry.bounds );
                                                   console.log( map.getBounds().toString() );
                                                          
                                               }
                                        )
                                   }
                            );
                        }
                    );
                }
            );
        </script>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Fuel Finder') ?></a>
                </div>
            </div>
        </nav>
        <div class="body">
            <div class="sidebar">
                <div><?php //echo $this->form( $this->geolocationForm ) ?></div>
                <div>
                    <ul id="results"></ul>
                </div>
            </div>
            <div class="main">
                <?php echo $this->content ?>
            </div> <!-- /container -->
        </div>
        <footer>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
