<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle( $this->translate('Fuel Finder') )->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile( 'http://maps.googleapis.com/maps/api/js?sensor=true', 'text/javascript' )
        ; ?>
        
        <script type="text/javascript">
            var map;
            var markers = Array();
            function initialise()
            {
                var mapOptions = {
                    center: new google.maps.LatLng( -34.397, 150.644 ),
                    zoom: 8
                };
                map = new google.maps.Map( document.getElementById( "map" ), mapOptions );
            }
            
            function positionMap( sw, ne )
            {
                map.fitBounds( new google.maps.LatLngBounds(
                        new google.maps.LatLng( sw.lat, sw.lng ),
                        new google.maps.LatLng( ne.lat, ne.lng ) )
                );
            }
            
            function getStations( lat, lng, radius )
            {
                var location = { 'lat': lat, 'lng': lng, 'buffer': radius };
                var directionsService = new google.maps.DirectionsService();
                $.get( '/petrolstations',
                       $.param( location ),
                       function( data )
                       {
                           var bounds = map.getBounds();
                           $.each( data,
                                   function( index1, pStation )
                                   {
                                       var start = new google.maps.LatLng( lat, lng );
                                       var latLng = new google.maps.LatLng( pStation[0].s_location.lat, pStation[0].s_location.lng );
                                       var request = { origin :start, destination: latLng, travelMode: google.maps.TravelMode.DRIVING };
                                       var distance = '';
                                       $( '#petrol tbody' ).append(
                                               $( '<tr/>', { id: 'station_' + pStation[0].s_id } ).append( $( '<td/>',
                                                                       { 'text': pStation[0].s_name } ) )
                                                           .append( $( '<td/>',
                                                                       { 'text': pStation.distance } ) )
                                                           
                                        );
                                       directionsService.route( request,
                                                                function( result, status )
                                                                {
                                                                    $( '#station_' + pStation[0].s_id ).append( $( '<td/>',
                                                                       { 'text': result.routes[0].legs[0].distance.value / 1000 } ) );
                                                                } );
                                       
                                       var marker = new google.maps.Marker( { 'title': pStation[0].s_name, 'position': latLng, 'map': map } );
                                       markers.push( marker );                                       
                                       bounds.extend( latLng );
                                       
                                   }
                            );
                            map.fitBounds( bounds );
                       }                                                                               
                );
            }
            
            $( 'document' ).ready(
                function()
                {
                    initialise();
                    $( "#geolocation" ).submit(
                        function( event )
                        {
                            $( '#results' ).empty();
                            $( '#petrol tbody' ).empty();
                            $.each( markers,
                                    function( index, marker )
                                    {
                                        marker.setMap( null );
                                    }
                            );
                            markers = Array();
                            event.preventDefault();
                            $.get( $( this ).attr( 'action' ),
                                   $( this ).serializeArray(),
                                   function( data )
                                   {                                       
                                       if( data.results.length === 1 )
                                       {
                                           positionMap( data.results[0].geometry.bounds.southwest, data.results[0].geometry.bounds.northeast );
                                           $( "#results" ).append( $( '<li/>',
                                                                      { 'text': data.results[0].formatted_address } )
                                                                    .click( function( event )
                                                                            {
                                                                                getStations( value.geometry.location.lat, value.geometry.location.lng, $( 'input[name=radius]' ).val() );                                                                        
                                                                            }
                                                                    )
                                                           );
                                       }
                                       else
                                       {
                                            $.each( data.results,
                                                function( index, value )
                                                {
                                                    $( "#results" ).append(
                                                            $( '<li/>',
                                                               { 'text': value.formatted_address } )
                                                            .click( function( event )
                                                                    {
                                                                        positionMap( value.geometry.bounds.southwest, value.geometry.bounds.northeast );
                                                                        $( this ).siblings().remove();
                                                                        getStations( value.geometry.location.lat, value.geometry.location.lng, $( 'input[name=radius]' ).val() );                                                                        
                                                                    }
                                                            )
                                                    );
                                                }
                                            );
                                        }
                                   }
                            );
                        }
                    );
                }
            );
        </script>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Fuel Finder') ?></a>
                </div>
            </div>
        </nav>
        <div class="body">
            <div class="sidebar">
                <div><?php echo $this->form( $this->geolocationForm ) ?></div>
                <div>
                    <h3>Point of interest</h3>
                    <p>( if more than one result click on the one you require )</p>
                    <ul id="results"></ul>
                    <h3>Petrol Stations</h3>                    
                    <table id="petrol">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Distance (km) </th>
                                <th>Travel distance (km)</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>                    
                </div>
            </div>
            <div class="main">
                <?php echo $this->content ?>
            </div> <!-- /container -->
        </div>
        <footer>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
